# Generated by Django 4.2.20 on 2025-05-08 13:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0005_main"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Main",
            new_name="Mail",
        ),
    ]
