# Generated by Django 4.2.20 on 2025-05-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_customer_order_shippingaddress_orderproduct"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="sity",
            new_name="city",
        ),
    ]
