# Generated by Django 4.2.20 on 2025-05-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_rename_sity_shippingaddress_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="title_en",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Имя категории"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="title_ru",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Имя категории"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(
                default="Здесь скоро будет описание",
                null=True,
                verbose_name="Описание товара",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ru",
            field=models.TextField(
                default="Здесь скоро будет описание",
                null=True,
                verbose_name="Описание товара",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="info_en",
            field=models.TextField(
                default="Дополнительная информация о товаре",
                null=True,
                verbose_name="Информация о товаре",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="info_ru",
            field=models.TextField(
                default="Дополнительная информация о товаре",
                null=True,
                verbose_name="Информация о товаре",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="title_en",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Наименование товара"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="title_ru",
            field=models.CharField(
                max_length=250, null=True, verbose_name="Наименование товара"
            ),
        ),
    ]
